# Generated by Django 5.2.7 on 2025-11-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='lot_number',
            field=models.IntegerField(null=True, verbose_name='Номер лота'),
        ),
        migrations.AddField(
            model_name='car',
            name='lot_url',
            field=models.TextField(null=True, verbose_name='URL Объявления'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(null=True, verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
