# Generated by Django 5.2.7 on 2025-11-23 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_lot_number_car_lot_url_car_mileage_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL для парсинга')),
                ('cars_parsed', models.IntegerField(default=0, verbose_name='Спарсено автомобилей')),
                ('images_parsed', models.IntegerField(default=0, verbose_name='Спарсено изображений')),
                ('status', models.CharField(default='running', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Лог парсинга',
                'verbose_name_plural': 'Логи парсинга',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='auction_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата аукциона'),
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер лота'),
        ),
        migrations.AlterField(
            model_name='car',
            name='lot_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL Объявления'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
