# Generated by Django 5.2.7 on 2025-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_parserlog_car_auction_date_car_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserlog',
            name='status',
            field=models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Завершен'), ('error', 'Ошибка')], default='running', max_length=20, verbose_name='Статус'),
        ),
    ]
